name: projeto_kva
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  responsive_sizer: ^3.0.5+1
  auto_size_text: ^3.0.0-nullsafety.0
  bottom_sheet: ^1.0.0
  calendar_timeline: ^1.0.0-null-safety.0
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.0.0
  dio: ^4.0.0-prev3
  flutter:
    sdk: flutter
  flutter_awesome_alert_box: ^2.0.0-prerelease-nullsafety
  flutter_holo_date_picker: ^1.0.0-nullsafety.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.0.0-nullsafety
  get: ^4.0.0-nullsafety.2
  get_storage: ^2.0.1
  getwidget: ^2.0.0-nullsafety.3
  google_fonts: ^2.0.0
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  pdf: ^3.6.1
  pie_chart: ^5.0.0
  roundcheckbox: ^2.0.0-nullsafety.0
  select_form_field: ^2.0.0
  sleek_circular_slider: ^2.0.0
  sn_progress_dialog: ^1.0.1
  spannable_grid: ^0.2.0
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/OpenSans-Regular.ttf
    - assets/images/logo_checklist.png
    - assets/images/logo.png
